https://www.intel.com/content/www/us/en/developer/topic-technology/artificial-intelligence/training/course-deep-learning.html

In [ ]:
import numpy as np

In [ ]:
x=np.arange(1,19).reshape(3,6)
print(x)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [ ]:
y=np.pad(x,pad_width=1,mode="constant",constant_values=5)
print(y)

[[ 5  5  5  5  5  5  5  5]
 [ 5  1  2  3  4  5  6  5]
 [ 5  7  8  9 10 11 12  5]
 [ 5 13 14 15 16 17 18  5]
 [ 5  5  5  5  5  5  5  5]]


In [ ]:
y=np.pad(x,pad_width=1,mode="edge")
print(y)


[[ 1  1  2  3  4  5  6  6]
 [ 1  1  2  3  4  5  6  6]
 [ 7  7  8  9 10 11 12 12]
 [13 13 14 15 16 17 18 18]
 [13 13 14 15 16 17 18 18]]


In [ ]:
y=np.pad(x,pad_width=1,mode="wrap")  #wrap is opposite
print(y)


[[18 13 14 15 16 17 18 13]
 [ 6  1  2  3  4  5  6  1]
 [12  7  8  9 10 11 12  7]
 [18 13 14 15 16 17 18 13]
 [ 6  1  2  3  4  5  6  1]]


In [ ]:
y=np.pad(x,pad_width=1,mode="reflect")  #it will reflect like that hide the first column and reflect second column
print(y)

[[ 8  7  8  9 10 11 12 11]
 [ 2  1  2  3  4  5  6  5]
 [ 8  7  8  9 10 11 12 11]
 [14 13 14 15 16 17 18 17]
 [ 8  7  8  9 10 11 12 11]]


In [ ]:
y=np.pad  (x,pad_width=1,mode="symmetric")# it will show the first row
print(y)

[[ 1  1  2  3  4  5  6  6]
 [ 1  1  2  3  4  5  6  6]
 [ 7  7  8  9 10 11 12 12]
 [13 13 14 15 16 17 18 18]
 [13 13 14 15 16 17 18 18]]


In [ ]:
y=np.pad  (x,pad_width=2,mode="symmetric")
print(y)

[[ 8  7  7  8  9 10 11 12 12 11]
 [ 2  1  1  2  3  4  5  6  6  5]
 [ 2  1  1  2  3  4  5  6  6  5]
 [ 8  7  7  8  9 10 11 12 12 11]
 [14 13 13 14 15 16 17 18 18 17]
 [14 13 13 14 15 16 17 18 18 17]
 [ 8  7  7  8  9 10 11 12 12 11]]


In [ ]:
y=np.pad(x,pad_width=1,mode='minimum')
y

array([[ 1,  1,  2,  3,  4,  5,  6,  1],
       [ 1,  1,  2,  3,  4,  5,  6,  1],
       [ 7,  7,  8,  9, 10, 11, 12,  7],
       [13, 13, 14, 15, 16, 17, 18, 13],
       [ 1,  1,  2,  3,  4,  5,  6,  1]])

In [ ]:
y=np.pad(x,pad_width=2,mode='minimum')
y

array([[ 1,  1,  1,  2,  3,  4,  5,  6,  1,  1],
       [ 1,  1,  1,  2,  3,  4,  5,  6,  1,  1],
       [ 1,  1,  1,  2,  3,  4,  5,  6,  1,  1],
       [ 7,  7,  7,  8,  9, 10, 11, 12,  7,  7],
       [13, 13, 13, 14, 15, 16, 17, 18, 13, 13],
       [ 1,  1,  1,  2,  3,  4,  5,  6,  1,  1],
       [ 1,  1,  1,  2,  3,  4,  5,  6,  1,  1]])

In [ ]:
y=np.pad(x,pad_width=1,mode='maximum')
y

array([[18, 13, 14, 15, 16, 17, 18, 18],
       [ 6,  1,  2,  3,  4,  5,  6,  6],
       [12,  7,  8,  9, 10, 11, 12, 12],
       [18, 13, 14, 15, 16, 17, 18, 18],
       [18, 13, 14, 15, 16, 17, 18, 18]])

In [ ]:
y=np.pad(x,pad_width=1,mode='mean')
y

array([[10,  7,  8,  9, 10, 11, 12, 10],
       [ 4,  1,  2,  3,  4,  5,  6,  4],
       [10,  7,  8,  9, 10, 11, 12, 10],
       [16, 13, 14, 15, 16, 17, 18, 16],
       [10,  7,  8,  9, 10, 11, 12, 10]])

In [ ]:
y=np.pad(x,pad_width=1,mode='median')
y

array([[10,  7,  8,  9, 10, 11, 12, 10],
       [ 4,  1,  2,  3,  4,  5,  6,  4],
       [10,  7,  8,  9, 10, 11, 12, 10],
       [16, 13, 14, 15, 16, 17, 18, 16],
       [10,  7,  8,  9, 10, 11, 12, 10]])

In [ ]:
y=np.pad(x,pad_width=5,mode="constant",constant_values=5)
print(y)

[[ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5]
 [ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5]
 [ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5]
 [ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5]
 [ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5]
 [ 5  5  5  5  5  1  2  3  4  5  6  5  5  5  5  5]
 [ 5  5  5  5  5  7  8  9 10 11 12  5  5  5  5  5]
 [ 5  5  5  5  5 13 14 15 16 17 18  5  5  5  5  5]
 [ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5]
 [ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5]
 [ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5]
 [ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5]
 [ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5]]


In [ ]:
y=np.pad(x,pad_width=2,mode="empty")
print(y)
# this no advisible dont use

[[    100528070367851                   0                 504
                   -1                 228                   0
   730183619550650400 2334097503649013792 8746397786911567457
  5773650044637547054]
 [8243122671947182689 3255293428008749683 3255307777713450285
  8246760658274623498 8246760658710853985 2334390082395404641
  2336082196527343215 2314885530818447950 8241904412978847776
  8079580276054385010]
 [2314885530450289761 8386944367493144944                   1
                    2                   3                   4
                    5                   6 8315181395361538150
  2334101988740001824]
 [7286935696384749428 2334675642003842916                   7
                    8                   9                  10
                   11                  12 5647343999915550050
  6877671131556421676]
 [7959303514749479246 7233185760977187177                  13
                   14                  15                  16
                   17                  1

In [ ]:
y=np.pad(x,pad_width=1,mode="linear_ramp")
y

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  0],
       [ 0,  7,  8,  9, 10, 11, 12,  0],
       [ 0, 13, 14, 15, 16, 17, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

# **While the image is comphersion the edges is blur so that,by using the padding method the edges can visibe some clear**

# **one of the use case of the numpy**

# **numpy**

In [ ]:
x=np.random.random(20)   #only 0-1
print(x)

[0.19957827 0.42552856 0.42679603 0.46919502 0.80985593 0.80330509
 0.11665728 0.11611192 0.21676139 0.89755194 0.58250288 0.61478749
 0.91101388 0.21247472 0.03182803 0.33115882 0.96622825 0.4839077
 0.91545626 0.95619398]


In [ ]:
x=np.random.random(20)*400
print(x)

[ 73.24096795 106.32128159 117.96384079 235.30603895 112.31525222
 192.88944649 197.81558066 105.58968354 347.84422593 141.15010088
 303.66181194  13.8841391  185.46773699 108.26006852 175.17167955
 136.80629358 204.73997834   3.2006779  352.76257867 206.82267698]


In [ ]:
x=np.random.randint(1,10,size=20)
print(x)

[8 4 8 2 7 6 2 2 3 7 4 7 4 4 2 1 2 9 9 1]


In [ ]:
x=np.random.randint(1,10,size=(3,4))
print(x)

[[3 7 1 3]
 [8 3 5 8]
 [5 4 6 4]]


In [ ]:
x=np.random.normal(size=(3,4))
print(x)

[[-0.00703876 -0.85848093  0.46180653  0.1210403 ]
 [-1.83682652  0.54711132 -0.48668425  0.53001779]
 [ 1.85994088 -1.11455452  0.88757937  1.18802021]]


In [ ]:
x=np.random.uniform(size=(3,4,7))
print(x)

[[[1.64263504e-01 8.04887821e-01 3.59606373e-01 1.72225223e-01
   4.85086027e-01 5.17230177e-01 4.72008737e-01]
  [5.06976420e-01 7.63699197e-01 6.38053109e-01 5.65963770e-01
   4.77223704e-01 4.72925176e-01 4.60592396e-02]
  [2.73293937e-01 4.01680409e-01 3.54869497e-01 8.42816418e-01
   3.97540131e-01 1.49011543e-01 2.64510451e-01]
  [1.94259297e-01 1.31461473e-02 4.31518873e-01 2.03611157e-01
   7.63143577e-01 2.15698915e-01 3.80505559e-01]]

 [[5.86232961e-01 4.37500265e-01 9.03162407e-02 4.67187848e-01
   8.27035090e-02 8.93911090e-01 8.28840270e-01]
  [4.98646647e-01 1.29414639e-01 1.90214218e-01 9.51362237e-01
   8.69948142e-01 8.27334008e-02 8.41624559e-01]
  [9.38425482e-01 1.08380478e-01 8.74009250e-02 5.12114734e-01
   2.44155131e-01 5.61798528e-01 2.50689697e-01]
  [7.80772509e-01 4.41090524e-01 7.14061082e-01 7.20862406e-01
   8.51873102e-01 2.15506367e-01 6.12942351e-01]]

 [[2.57719708e-01 5.35624719e-01 3.55360901e-01 2.06787420e-01
   1.80607452e-01 3.96320623e-01 7.18

In [ ]:
x=np.array([1,2,3,4,5])
print(x)
np.random.shuffle(x)  #SHUFFLE MEANS ARRANGEMENT
print(x)

[1 2 3 4 5]
[1 5 4 2 3]


In [ ]:
#[perumentation]    possibility of arrangement

#a b c d
#a b d c
#a c b d
#a c d b
#a d b c
#a d c b

In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9,0])
print(x)



[1 2 3 4 5 6 7 8 9 0]


In [ ]:
import itertools as it

y=it.permutations(x,r=4)
for i in y:
  print(i)

Streaming output truncated to the last 5000 lines.
(1, 2, 8, 9)
(1, 2, 8, 0)
(1, 2, 9, 3)
(1, 2, 9, 4)
(1, 2, 9, 5)
(1, 2, 9, 6)
(1, 2, 9, 7)
(1, 2, 9, 8)
(1, 2, 9, 0)
(1, 2, 0, 3)
(1, 2, 0, 4)
(1, 2, 0, 5)
(1, 2, 0, 6)
(1, 2, 0, 7)
(1, 2, 0, 8)
(1, 2, 0, 9)
(1, 3, 2, 4)
(1, 3, 2, 5)
(1, 3, 2, 6)
(1, 3, 2, 7)
(1, 3, 2, 8)
(1, 3, 2, 9)
(1, 3, 2, 0)
(1, 3, 4, 2)
(1, 3, 4, 5)
(1, 3, 4, 6)
(1, 3, 4, 7)
(1, 3, 4, 8)
(1, 3, 4, 9)
(1, 3, 4, 0)
(1, 3, 5, 2)
(1, 3, 5, 4)
(1, 3, 5, 6)
(1, 3, 5, 7)
(1, 3, 5, 8)
(1, 3, 5, 9)
(1, 3, 5, 0)
(1, 3, 6, 2)
(1, 3, 6, 4)
(1, 3, 6, 5)
(1, 3, 6, 7)
(1, 3, 6, 8)
(1, 3, 6, 9)
(1, 3, 6, 0)
(1, 3, 7, 2)
(1, 3, 7, 4)
(1, 3, 7, 5)
(1, 3, 7, 6)
(1, 3, 7, 8)
(1, 3, 7, 9)
(1, 3, 7, 0)
(1, 3, 8, 2)
(1, 3, 8, 4)
(1, 3, 8, 5)
(1, 3, 8, 6)
(1, 3, 8, 7)
(1, 3, 8, 9)
(1, 3, 8, 0)
(1, 3, 9, 2)
(1, 3, 9, 4)
(1, 3, 9, 5)
(1, 3, 9, 6)
(1, 3, 9, 7)
(1, 3, 9, 8)
(1, 3, 9, 0)
(1, 3, 0, 2)
(1, 3, 0, 4)
(1, 3, 0, 5)
(1, 3, 0, 6)
(1, 3, 0, 7)
(1, 3, 0, 8)
(1, 3, 0, 9)
(1, 4, 2, 3)
